# Generated by Django 4.0.3 on 2022-03-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('postulant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulant',
            name='document',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='document_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commons.documenttype'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='gender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commons.gender'),
        ),
    ]
