# Generated by Django 4.0.3 on 2022-03-17 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('name_original', models.CharField(max_length=100, verbose_name='Nombre original')),
                ('format', models.CharField(max_length=100, verbose_name='Formato')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='postulant',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postulant.curriculum', verbose_name='Curriculum'),
        ),
    ]
