# Generated by Django 4.0.3 on 2022-03-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('postulant', '0002_alter_postulant_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulant',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.documenttype'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.gender'),
        ),
    ]
