# Generated by Django 4.0.3 on 2022-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0003_alter_postulant_document_type_alter_postulant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulant',
            name='document',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
