# Generated by Django 4.0.3 on 2022-03-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('postulant', '0001_initial'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulate',
            name='postulant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulant.postulant'),
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.address'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrole'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workarea'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workexperience'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workmodality'),
        ),
        migrations.AddField(
            model_name='job',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workday'),
        ),
    ]
