# Generated by Django 4.0.3 on 2022-03-15 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ruc', models.CharField(max_length=250, unique=True, verbose_name='RUC')),
                ('email', models.EmailField(help_text='Correo', max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=250)),
                ('business_name', models.CharField(max_length=250, verbose_name='Razon Social')),
                ('tradename', models.CharField(max_length=250, verbose_name='Razon Social')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
