# Generated by Django 4.0.3 on 2022-03-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_email_remove_company_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, verbose_name='RUC'),
        ),
    ]
