# Generated by Django 4.0.3 on 2022-03-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_ruc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='business_name',
            new_name='bussiness_name',
        ),
    ]
