# Generated by Django 4.0.3 on 2022-03-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_delete_category'),
        ('companies', '0003_alter_company_address_alter_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.businesssector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='foundation_year',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
