# Generated by Django 4.0.3 on 2022-03-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_address_alter_company_business_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='foundation_year',
            field=models.CharField(blank=True, default=0, max_length=4, null=True),
        ),
    ]
