# Generated by Django 4.0.3 on 2022-03-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_business_name_company_bussiness_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bussiness_name',
            new_name='business_name',
        ),
    ]
