# Generated by Django 4.0.3 on 2022-03-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_foundation_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
        migrations.DeleteModel(
            name='WorkArea',
        ),
        migrations.DeleteModel(
            name='WorkDay',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.DeleteModel(
            name='WorkModality',
        ),
    ]
